version: '3.7'


services:
  web:
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=geo.front.localhost
    volumes:
      - ./:/geo-front

networks:
  default:
    external:
      name: nginx-proxy
