version: '3.7'


services:
  frontend-docker-app:
    container_name: docker-front-apps
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/app
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true

  web:
    container_name: web-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - VIRTUAL_HOST=geo.front.localhost
    volumes:
      - ./:/geo-front
      - ./docker/entrypoint.sh:/app/entrypoint.sh
    depends_on:
      - frontend-docker-app
   # entrypoint: ["/app/entrypoint.sh"]


networks:
  default:
    external:
      name: nginx-proxy
